# .github/workflows/pages.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build and deploy
        uses: helaili/jekyll-action@v2.0.0
        with:
          jekyll_src: .
          jekyll_dest: ./_site
        env:
          JEKYLL_ENV: production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
          branch: master
