name: Auto Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Jekyll
        uses: jekyllrb/action-jekyll-build@v1.6.0
        with:
          destination: ./_site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: _site